# Generated by Django 5.2.1 on 2025-06-07 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('customer_reference_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('city_state', models.CharField(max_length=200)),
                ('guarantor_name', models.CharField(max_length=200)),
                ('guarantor_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('down_payment_percent', models.CharField(max_length=10)),
                ('loan_period_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('property_insurance_per_month', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('reduced_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('down_payment_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('annual_principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monthly_principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('final_principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interest_per_annum', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_interest_for_period', models.DecimalField(decimal_places=2, max_digits=20)),
                ('final_total_interest', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pmi_per_annum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Processed Data 2',
                'verbose_name_plural': 'Processed Data 2',
            },
        ),
    ]
