# Generated by Django 5.2.1 on 2025-06-07 12:36

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processeddata2',
            options={'ordering': ['image_number', 'serial_number', '-entry_timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='processeddata2',
            unique_together={('image_number', 'serial_number')},
        ),
        migrations.AddField(
            model_name='processeddata2',
            name='purchase_value_excel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='city_state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='customer_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='customer_reference_number',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='down_payment_percent',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='entry_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='final_principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='guarantor_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='guarantor_reference_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='image_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='loan_period_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='property_insurance_per_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='serial_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='total_interest_for_period',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata2',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='processeddata2',
            name='annual_principal',
        ),
        migrations.RemoveField(
            model_name='processeddata2',
            name='down_payment_value',
        ),
        migrations.RemoveField(
            model_name='processeddata2',
            name='final_total_interest',
        ),
        migrations.RemoveField(
            model_name='processeddata2',
            name='interest_per_annum',
        ),
        migrations.RemoveField(
            model_name='processeddata2',
            name='monthly_principal',
        ),
        migrations.RemoveField(
            model_name='processeddata2',
            name='purchase_value',
        ),
        migrations.RemoveField(
            model_name='processeddata2',
            name='reduced_value',
        ),
    ]
