# Generated by Django 4.2.7 on 2025-06-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_processeddata2_assessment_rate_reduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata2',
            name='assessment_rate_reduction',
        ),
        migrations.RemoveField(
            model_name='processeddata2',
            name='property_tax_for_loan_period',
        ),
    ]
