# Generated by Django 4.2.7 on 2025-06-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_remove_processeddata2_assessment_rate_reduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata2',
            name='assessment_reduction_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='processeddata2',
            name='property_tax_for_period',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='processeddata2',
            name='property_tax_per_annum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
