# Generated by Django 5.2.1 on 2025-06-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name_input', models.TextField()),
                ('guarantor_name_input', models.TextField()),
                ('city_state_input', models.TextField()),
                ('purchase_value_entered_input', models.TextField()),
                ('purchase_value_reduction_percent_input', models.DecimalField(decimal_places=2, max_digits=5)),
                ('down_payment_percent_input', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_period_years_input', models.IntegerField()),
                ('monthly_principal_reduction_percent_input', models.DecimalField(decimal_places=2, max_digits=5)),
                ('processed_customer_name', models.TextField()),
                ('processed_guarantor_name', models.TextField()),
                ('processed_city_state', models.TextField()),
                ('processed_original_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('processed_reduced_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('processed_pv_enter_excel', models.DecimalField(decimal_places=2, max_digits=20)),
                ('processed_dp_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('processed_loan_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('processed_annual_principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('processed_monthly_principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('processed_final_principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
