# Generated by Django 5.0.2 on 2025-06-09 06:04

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_number', models.CharField(max_length=50)),
                ('serial_number', models.IntegerField()),
                ('username', models.CharField(default='', max_length=200)),
                ('customer_reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.TextField()),
                ('city_state', models.TextField()),
                ('purchase_value_excel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('down_payment_percent', models.CharField(default='0', max_length=10)),
                ('loan_period_years', models.IntegerField(default=0)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('guarantor_name', models.TextField(default='')),
                ('guarantor_reference_number', models.TextField(blank=True, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('final_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_interest_for_period', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('property_insurance_per_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('pmi_per_annum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('entry_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['image_number', 'serial_number', '-entry_timestamp'],
                'unique_together': {('image_number', 'serial_number')},
            },
        ),
    ]
