# Generated by Django 5.2.1 on 2025-06-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='processeddata',
            name='quality_checked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='quality_checked_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='processed_final_principal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
