# Generated by Django 5.2.1 on 2025-06-04 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_processeddata_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processeddata',
            options={'ordering': ['image_number', 'serial_number', '-entry_timestamp']},
        ),
        migrations.AddField(
            model_name='processeddata',
            name='entry_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='image_number',
            field=models.CharField(blank=True, help_text='Enter the image number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='serial_number',
            field=models.IntegerField(blank=True, help_text='Serial number within the image', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='processeddata',
            unique_together={('image_number', 'serial_number')},
        ),
    ]
