# Generated by Django 5.2.1 on 2025-06-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_processeddata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='image_number',
            field=models.CharField(help_text='Enter the image number', max_length=50),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='serial_number',
            field=models.IntegerField(help_text='Serial number within the image'),
        ),
    ]
