# Generated by Django 5.2.1 on 2025-06-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_processeddata_image_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='city_state_input',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='customer_name_input',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='down_payment_percent_input',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='guarantor_name_input',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='loan_period_years_input',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='monthly_principal_reduction_percent_input',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='purchase_value_entered_input',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='purchase_value_reduction_percent_input',
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='image_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='quality_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='serial_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='status',
            field=models.CharField(default='processed', max_length=50),
        ),
    ]
