# Generated by Django 4.2.7 on 2025-06-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_processeddata_assessment_reduction_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='assessment_reduction_rate',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='property_tax_for_period',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='property_tax_per_annum',
        ),
    ]
