# Generated by Django 5.2.1 on 2025-06-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_processeddata_city_state_input_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processeddata',
            old_name='processed_annual_principal',
            new_name='annual_principal',
        ),
        migrations.RenameField(
            model_name='processeddata',
            old_name='processed_city_state',
            new_name='city_state',
        ),
        migrations.RenameField(
            model_name='processeddata',
            old_name='processed_customer_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='processeddata',
            old_name='processed_dp_value',
            new_name='down_payment_value',
        ),
        migrations.RenameField(
            model_name='processeddata',
            old_name='processed_final_principal',
            new_name='final_principal',
        ),
        migrations.RenameField(
            model_name='processeddata',
            old_name='processed_guarantor_name',
            new_name='guarantor_name',
        ),
        migrations.RenameField(
            model_name='processeddata',
            old_name='processed_loan_amount',
            new_name='loan_amount',
        ),
        migrations.RenameField(
            model_name='processeddata',
            old_name='processed_monthly_principal',
            new_name='monthly_principal',
        ),
        migrations.RenameField(
            model_name='processeddata',
            old_name='processed_original_amount',
            new_name='purchase_value',
        ),
        migrations.RenameField(
            model_name='processeddata',
            old_name='processed_pv_enter_excel',
            new_name='purchase_value_excel',
        ),
        migrations.RenameField(
            model_name='processeddata',
            old_name='processed_reduced_value',
            new_name='reduced_purchase_value',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='quality_checked_at',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='quality_checked_by',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='status',
        ),
    ]
