# Generated by Django 4.2.7 on 2025-06-14 08:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_processeddata_assessment_reduction_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='assessment_reduction_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='property_tax_for_period',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='property_tax_per_annum',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
