# Generated by Django 5.2.1 on 2025-06-04 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_processed_annual_principal_processeddata_annual_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_number', models.CharField(max_length=50)),
                ('serial_number', models.IntegerField()),
                ('customer_name', models.TextField()),
                ('city_state', models.TextField()),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reduced_purchase_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchase_value_excel', models.DecimalField(decimal_places=2, max_digits=20)),
                ('down_payment_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('annual_principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monthly_principal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('final_principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guarantor_name', models.TextField()),
                ('test_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('original_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.processeddata')),
            ],
            options={
                'ordering': ['image_number', 'serial_number', '-test_timestamp'],
                'unique_together': {('image_number', 'serial_number')},
            },
        ),
    ]
