# Generated by Django 4.2.7 on 2025-06-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_processeddata_assessment_reduction_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='assessment_reduction_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='property_tax_for_period',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='property_tax_per_annum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
