# Generated by Django 5.2.1 on 2025-06-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_processeddata_customer_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='guarantor_reference_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testingdata',
            name='guarantor_reference_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
