# Generated by Django 5.2.1 on 2025-06-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_processeddata_guarantor_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='customer_reference_number',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
