# Generated by Django 5.2.1 on 2025-06-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_processeddata_customer_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='annual_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='down_payment_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='final_total_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='interest_per_annum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='loan_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='loan_period_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='monthly_principal_reduction_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='pmi_per_annum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='pmi_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='property_insurance_per_annum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='property_insurance_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='property_insurance_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='purchase_value_reduction_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='total_interest_for_period',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='total_interest_reduction_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='final_principal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
