# Generated by Django 5.2.1 on 2025-06-05 13:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_processeddata_annual_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='annual_principal',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='down_payment_value',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='final_total_interest',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='interest_per_annum',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='loan_percentage',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='monthly_principal',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='monthly_principal_reduction_percent',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='pmi_rate',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='property_insurance_per_annum',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='property_insurance_rate',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='purchase_value',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='purchase_value_reduction_percent',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='reduced_purchase_value',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='total_interest_reduction_percent',
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='down_payment_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='final_principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='guarantor_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='loan_period_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='property_insurance_per_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='purchase_value_excel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='total_interest_for_period',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
