# Generated by Django 5.2.1 on 2025-06-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_processeddata_annual_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='down_payment_percent',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
