# Generated by Django 5.2.1 on 2025-06-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_processeddata_down_payment_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityStateAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('assessment_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'City and State Assessment Rate',
                'verbose_name_plural': 'City and State Assessment Rates',
                'unique_together': {('city', 'state')},
            },
        ),
    ]
