# Generated by Django 5.2.1 on 2025-06-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_citystateassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.TextField()),
                ('assessment_rate', models.TextField()),
                ('row_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Excel Data Entry',
                'verbose_name_plural': 'Excel Data Entries',
                'ordering': ['row_number'],
            },
        ),
    ]
