# Generated by Django 5.2.1 on 2025-06-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_exceldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityStateAssessment',
        ),
    ]
