# Generated by Django 5.2.1 on 2025-06-07 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_exceldata_options_exceldata_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelData',
        ),
        migrations.AlterModelOptions(
            name='processeddata',
            options={'ordering': ('-test_timestamp',), 'verbose_name': 'Processed Data', 'verbose_name_plural': 'Processed Data'},
        ),
        migrations.AlterUniqueTogether(
            name='processeddata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='test_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='test_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='TestingData',
        ),
    ]
