# Generated by Django 5.2.1 on 2025-06-07 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_exceldata_alter_processeddata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.TextField()),
                ('assessment_rate', models.TextField()),
                ('row_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Excel Data Entry',
                'verbose_name_plural': 'Excel Data Entries',
                'ordering': ['row_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='processeddata',
            options={'ordering': ['image_number', 'serial_number', '-entry_timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='processeddata',
            unique_together={('image_number', 'serial_number')},
        ),
        migrations.AddField(
            model_name='processeddata',
            name='annual_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='down_payment_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='monthly_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='reduced_purchase_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='city_state',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='customer_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='customer_reference_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='down_payment_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='final_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='image_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='pmi_per_annum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='property_insurance_per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='test_data',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='test_timestamp',
        ),
        migrations.CreateModel(
            name='TestingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_number', models.CharField(default='', max_length=50)),
                ('serial_number', models.IntegerField(default=0)),
                ('customer_reference_number', models.TextField(blank=True, null=True)),
                ('customer_name', models.TextField(default='')),
                ('city_state', models.TextField(default='')),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reduced_purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('purchase_value_excel', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('down_payment_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('annual_principal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('monthly_principal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('final_principal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('guarantor_name', models.TextField(default='')),
                ('guarantor_reference_number', models.TextField(blank=True, null=True)),
                ('test_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('original_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.processeddata')),
            ],
            options={
                'ordering': ['image_number', 'serial_number', '-test_timestamp'],
                'unique_together': {('image_number', 'serial_number')},
            },
        ),
    ]
