# Generated by Django 5.2.1 on 2025-06-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_exceldata_alter_processeddata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceldata',
            options={'ordering': ['row_number'], 'verbose_name': 'Excel Data', 'verbose_name_plural': 'Excel Data'},
        ),
        migrations.AddField(
            model_name='exceldata',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='assessment_rate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceldata',
            name='city_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
