# Generated by Django 5.2.1 on 2025-06-07 10:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_exceldata_options_exceldata_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='annual_principal',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='down_payment_value',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='monthly_principal',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='purchase_value',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='reduced_purchase_value',
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='city_state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='customer_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='customer_reference_number',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='down_payment_percent',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='final_principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='image_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='pmi_per_annum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='property_insurance_per_month',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='serial_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='annual_principal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='city_state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='customer_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='down_payment_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='final_principal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='guarantor_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='image_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='monthly_principal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='purchase_value_excel',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='reduced_purchase_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='testingdata',
            name='serial_number',
            field=models.IntegerField(),
        ),
    ]
