# Generated by Django 5.2.1 on 2025-06-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_processeddata_annual_principal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelData',
        ),
    ]
