# Generated by Django 5.2.1 on 2025-06-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_delete_exceldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestingData',
        ),
    ]
