# Generated by Django 5.2.1 on 2025-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_testingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
