# Generated by Django 4.2.7 on 2025-06-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='annual_interest_rate_percent',
            field=models.CharField(max_length=20, verbose_name='Annual Interest Rate %'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='assessment_reduction_rate_percent',
            field=models.CharField(max_length=20, verbose_name='Assessment Reduction Rate %'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='down_payment_percent',
            field=models.CharField(max_length=20, verbose_name='Down Payment %'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='loan_period_years',
            field=models.CharField(max_length=10, verbose_name='Loan Period (Years)'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='monthly_principal_reduction_percent',
            field=models.CharField(max_length=20, verbose_name='Monthly Principal Reduction %'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='purchase_value',
            field=models.CharField(max_length=50, verbose_name='Purchase Value'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='purchase_value_reduction_percent',
            field=models.CharField(max_length=20, verbose_name='Purchase Value Reduction %'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='total_interest_reduction_percent',
            field=models.CharField(max_length=20, verbose_name='Total Interest Reduction %'),
        ),
    ]
