# Generated by Django 4.2.7 on 2025-06-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_alter_customerdata_annual_interest_rate_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='customer_reference_number',
            field=models.CharField(max_length=300, unique=True, verbose_name='Customer Reference Number'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='guarantor_reference_number',
            field=models.CharField(max_length=300, verbose_name='Guarantor Reference Number'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='purchase_value',
            field=models.CharField(max_length=500, verbose_name='Purchase Value'),
        ),
    ]
