# Generated by Django 4.2.7 on 2025-06-20 17:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, verbose_name='Emp ID')),
                ('image_number', models.IntegerField(verbose_name='Image Number')),
                ('serial_number', models.IntegerField(verbose_name='Serial Number')),
                ('customer_reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.TextField()),
                ('city_state', models.TextField()),
                ('purchase_value_excel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('purchase_value_reduction_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('down_payment_percent', models.CharField(default='0', max_length=10)),
                ('loan_period_years', models.IntegerField(default=0)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('guarantor_name', models.TextField(default='')),
                ('guarantor_reference_number', models.TextField(blank=True, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('final_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_interest_for_period', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('property_insurance_per_month', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('pmi_per_annum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('assessment_reduction_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('property_tax_per_annum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('property_tax_for_period', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Processed Data 5',
                'verbose_name_plural': 'Processed Data 5',
                'ordering': ['image_number', 'serial_number', '-created_at'],
            },
        ),
    ]
