# Generated by Django 4.2.7 on 2025-06-21 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedData5',
        ),
    ]
